spring:
  application:
    name: wishlist-support-api
  data:
    mongodb:
      authentication-database: admin
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
  cloud:
    kubernetes:
      secrets:
        name: mongo-wl-sup-secret
      config:
        enabled: true
        sources:
          - namespace: default
            name: mongo-wl-sup-conf
      reload:
        enabled: true
        mode: polling
        period: 1000
spring-doc:
  packagesToScan: com.raytotti.wishlist.support
  version: "1.0.0"
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true


