spring:
  application:
    name: wishlist-support-api
  data:
    mongodb:
      authentication-database: admin
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
  cloud:
    kubernetes:
      secrets:
        name: mongo-wishlist-support-secret
      config:
        enabled: true
        sources:
          - namespace: default
            name: mongo-wishlist-support-conf
      reload:
        enabled: true
        mode: polling
        period: 1000
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true


