kind: Service
apiVersion: v1
metadata:
  name: wishlist-support-api
spec:
  selector:
    app: wishlist-support-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-support-api
spec:
  selector:
    matchLabels:
      app: wishlist-support-api
  replicas: 2
  template:
    metadata:
      labels:
        app: wishlist-support-api
    spec:
      containers:
        - name: wishlist-support-api
          image: wishlist-support-api:1.0
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-wl-sup-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-wl-sup-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-wl-sup-conf
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-wl-sup-conf
                  key: host